export * from './withAddAppActivity';
export * from './withAddAppActivityAndroidManifest';
export * from './withAddReleaseSigningConfigBuildGradle';
export * from './withCopyTemplateJavaFile';
export * from './withRemoveUsesClearTextTraffic';
export * from './withDisabledWindowDrawsSystemBarBackgrounds';
export * from './withEnabledStatusBarTranslucent';
export * from './withCopyMainActivity';
export * from './withMoveDevSettingsActivityToDebugAndroidManifest';
