export * from './withAddAppActivity';
export * from './withAddAppActivityAndroidManifest';
export * from './withAppBuildGradleForRelease';
export * from './withCopyTemplateJavaFile';
export * from './withRemoveUsesClearTextTrafficForRelease';
export * from './withDisabledWindowDrawsSystemBarBackgrounds';
export * from './withEnabledStatusBarTranslucent';
export * from './withCopyMainActivity';
export * from './withMoveDevSettingsActivityToDebugAndroidManifest';
