/**
 * Copyright 2023 TIS Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * SantokuApp REST API
 * SantokuAppのREST API。
 * OpenAPI spec version: 1.0.0
 */
import type {Tag} from './tag';

/**
 * 質問内容
 */
export interface QuestionContent {
  /** 質問ID */
  readonly questionId: string;
  /** 質問のタイトル */
  title: string;
  /** 質問内容 */
  content: string;
  /** 質問に設定されているタグ */
  tags: Tag[];
  /** 質問日時 */
  datetime: string;
  /** 初心者か否か */
  beginner: boolean;
  /** 解決済か否か */
  resolved: boolean;
  /** 閲覧数 */
  views: number;
  /** 回答数 */
  answers: number;
  /** いいね数 */
  likes: number;
  /** コメント数 */
  comments: number;
  /** 最終更新日 */
  lastUpdatedAt?: string;
}
