import "Fastfile.build_santoku_app_ios"
import "Fastfile.prebuild_santoku_app_ios"
import "Fastfile.prebuild_santoku_app_android"

################################################################################
# DeployGateへのデプロイに関する注意点
### Android App Bundle
# DeployGateのAndroid App Bundleサポートには制限がありますが、Google Playにはaab形式でリリースする必要があるので、
# DeployGateへのアップロードにもaab形式を利用します。
#   https://intercom.help/deploygate/ja/articles/4536522
# - 対象のアプリ（APK形式）が事前にアップロードされていて、アップロード鍵が設定されている必要があります
# - Dynamic Delivery 等の App Bundle 特有の機能は動作しません
# - 端末最適化された APKS の配布には対応していません
################################################################################

platform :ios do

  desc "Build SantokuApp Production Release"
  lane :prod do
    prebuild_santoku_app_ios(environment: "prod")
    build_santoku_app_ios(environment: "prod")
  end

  desc "Build SantokuApp Staging Release"
  lane :stg do
    prebuild_santoku_app_ios(environment: "stg")
    build_santoku_app_ios(environment: "stg")
  end

end

platform :android do

  desc "Build SantokuApp Production Release"
  lane :prod do
    prebuild_santoku_app_android(environment: "prod")
    build_android_app(task: "bundle", build_type: "Release", project_dir: "android")
  end

  desc "Build SantokuApp Staging Release"
  lane :stg do
    prebuild_santoku_app_android(environment: "stg")
    build_android_app(task: "bundle", build_type: "Release", project_dir: "android")
  end

end
