/**
 * Copyright 2023 TIS Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * SantokuApp Sandbox REST API
 * SantokuApp Sandbox REST API
 * OpenAPI spec version: 1.0.0
 */
import type {Todo} from './todo';

/**
 * ListTodoResponse
 */
export interface ListTodoResponse {
  /** Current page number */
  number?: number;
  /** Page size */
  size?: number;
  /** Sort key */
  sort?: string;
  /** Number of current page elements. */
  numberOfElements?: number | null;
  /** Total elements */
  totalElements?: number;
  /** Total pages */
  totalPages?: number;
  content?: Todo[];
  /** Whether the content is empty */
  empty?: boolean;
  /** Whether this page is the first page */
  first?: boolean;
  /** Whether this page is the last page */
  last?: boolean;
}
