language: java
branches:
  only:
  - master
  - develop
install: true
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
script:
- git clone -b master https://github.com/nablarch/nablarch-ci-script.git $HOME/build-script/
  && chmod +x $HOME/build-script/travis-ci/*.sh
- $HOME/build-script/travis-ci/prepare_travis_settings.sh
- $HOME/build-script/travis-ci/gsp-gen.sh -p gsp
- $HOME/build-script/travis-ci/build-nablarch.sh -p development
- travis_wait 30 $HOME/build-script/travis-ci/upload-test-report.sh -p dev-deploy
notifications:
  slack:
    secure: Pur8g9Y5gjZJ2+ngmuOX5Drbt/mjM2DeEkO03alZyl9Cm/iA9/YjeBlk3j0WNS9L4XqQRiqDgJ1KdMVx5ZdjwpZjTRkEVtx/oBxHXEJYi80b52m1ePK1QVddWG1wls1vCkI3uTBnHzyQxB0QWFy5EW3+PiTYudTn7b6bRrU8HBwAIQ90sqyNYZIjqewciIShIRorFL/UgWsflZ6E6QNUjnXEB91w93fLUEge3oaB1VBSP8u1gMR121JmrSOxkEkmqj2lo2JneKgPmM7YlW1wR8BxjUPPkelcEkW9Wq6LeLaXSdj3pR30EWqSYZw0D+OsXmam0r+Fwov/P6ueMR/xHm2lFkS6O1Yg06J/VZJTi5iKl4Dahz2jI+zsd06zcq1DLK0AOAGFF2TrMS1Z8ubrdl8EsapvJ57+0GwWpct+p6Q9ISvUlaQnf0Sd1ZbdEGYD7Tefi7Gp8Neo/4Kc324REATCMsWg/9OoKp8s5Ow5Qn9PvIe9MH9thtH0HWwgU+JCtKRjEBj69plaNxNblGuKk4b2wsZuQtmsdSMRiqXum7Qn59NdWw9ckEKpMGweShX2Zs4++8mF+csmYJNAKyhxfgjdJGz4ECAgYKDMAJsRQveEiHu631SYgrugRJaQOUfeosJkbeQsvwT/O1YcvqyV7MhafF83MO1UXBHZUXFYzrY=
