import {
  getAccountsMe,
  useGetAccountsAccountId,
  useGetAccountsAccountIdAvatar,
  useGetAccountsMe,
  useGetAccountsMeAvatar,
  useGetAccountsMeTerms,
  usePostAccountsMeDeviceToken,
  usePostAccountsMeTerms,
  usePostLogin,
  usePostLogout,
  usePostSignup,
  usePutAccountsMeAvatar,
  useDeleteAccountsMeDelete,
} from 'generated/backend/account/account';

export {
  getAccountsMe,
  useGetAccountsAccountId,
  useGetAccountsAccountIdAvatar,
  useGetAccountsMe,
  useGetAccountsMeAvatar,
  useGetAccountsMeTerms,
  usePostAccountsMeDeviceToken,
  usePostAccountsMeTerms,
  usePostLogin,
  usePostLogout,
  usePostSignup,
  usePutAccountsMeAvatar,
  useDeleteAccountsMeDelete,
};
