parameters:
- name: environments
  type: object
  default:
    - name: 'stg'
      laneName: 'stg'
      androidAppPath: 'android/app/build/outputs/bundle/release/app-release.aab'
      iOSAppPath: 'ios/build/santoku-app-stg.ipa'
    - name: 'dev'
      laneName: 'dev'
      androidAppPath: 'android/app/build/outputs/bundle/debug/app-debug.aab'
      iOSAppPath: 'ios/build/santoku-app-dev.ipa'

variables:
- group: android
- group: apple
- group: deployGate
- group: santokuAppStg
- group: santokuAppDev
- group: temp-cert-test-2025-06-02
- name: appDir
  value: '$(System.DefaultWorkingDirectory)/example-app/SantokuApp'
- name: branchName
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/') }}:
    value: $[ replace(variables['Build.SourceBranch'], 'refs/heads/', '') ]
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/pull/') }}:
    value: $[ replace(variables['System.PullRequest.SourceBranch'], 'refs/heads/', '') ]
- name: npmConfigCache
  value: '$(Pipeline.Workspace)/.npm'

stages:
- ${{ each environment in parameters.environments }}:
  - stage: iOS_${{environment.name}}
    displayName: iOS_${{environment.name}}
    dependsOn: []
    jobs:
    - job: build_${{environment.name}}
      displayName: 'build ${{environment.name}}'
      pool:
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md
        vmImage: macOS-14
      steps:
      - task: UseRubyVersion@0
        inputs:
          versionSpec: '3.1'
          addToPath: true
      - task: InstallAppleCertificate@2
        displayName: 'Install an Apple certificate for ${{environment.name}}'
        inputs:
          certSecureFile: $(apple_DevelopmentCertificateSecureFileName)
          certPwd: $(apple_DevelopmentCertificatePassword)
      - task: InstallAppleCertificate@2
        displayName: 'Install an Apple certificate for ${{environment.name}}'
        inputs:
          certSecureFile: $(apple_DistributionCertificateSecureFileName_for_cert_test_2025_06_02)
          certPwd: $(apple_DistributionCertificatePassword_for_cert_test_2025_06_02)
      - task: InstallAppleProvisioningProfile@1
        displayName: 'Install an Apple provisioning profile for ${{environment.name}}'
        inputs:
          provProfileSecureFile: $(${{environment.name}}_AppleDevelopmentProvisioningProfileSecureFileName)
      - task: InstallAppleProvisioningProfile@1
        displayName: 'Install an Apple provisioning profile for ${{environment.name}}'
        inputs:
          provProfileSecureFile: $(${{environment.name}}_AppleDistributionProvisioningProfileSecureFileName_for_cert_test_2025_06_02)
      - task: CmdLine@2
        displayName: 'Use Xcode 15.4'
        inputs:
          script: 'sudo xcode-select --switch /Applications/Xcode_15.4.app'
      - task: NodeTool@0
        displayName: 'Use Node.js 20.17.0'
        inputs:
          versionSpec: '20.17.0'
      - task: Cache@2
        displayName: Cache npm
        inputs:
          key: 'npm | "$(Agent.OS)" | $(appDir)/package-lock.json'
          restoreKeys: |
            npm | "$(Agent.OS)"
          path: $(npmConfigCache)
      - task: CmdLine@2
        displayName: 'npm ci --cache $(npmConfigCache)'
        inputs:
          script: 'npm ci --cache $(npmConfigCache)'
          workingDirectory: '$(appDir)'
      - task: CmdLine@2
        displayName: 'bundle install'
        inputs:
          script: 'bundle install'
          workingDirectory: '$(appDir)'
      - task: DownloadSecureFile@1
        displayName: 'Download GoogleServices-Info.plist file for ${{environment.name}}'
        inputs:
          secureFile: $(${{environment.name}}_GoogleServicesInfoPlistSecureFileName)
      - task: CopyFiles@2
        displayName: 'Copy GoogleService-Info.plist file to: $(appDir)'
        inputs:
          SourceFolder: '$(Agent.TempDirectory)'
          Contents: $(${{environment.name}}_GoogleServicesInfoPlistSecureFileName)
          TargetFolder: '$(appDir)'
      - task: CmdLine@2
        displayName: 'Rename GoogleService-Info.plist'
        inputs:
          script: |
            /bin/mv $(${{environment.name}}_GoogleServicesInfoPlistSecureFileName) GoogleService-Info.plist
          workingDirectory: '$(appDir)'
      - task: CmdLine@2
        displayName: 'Prebuild iOS app for ${{environment.name}}'
        inputs:
          script: 'fastlane ios prebuild_${{environment.laneName}}'
          workingDirectory: '$(appDir)'
      - task: CmdLine@2
        displayName: 'Build iOS app for ${{environment.name}}'
        inputs:
          script: 'fastlane ios build_${{environment.laneName}}'
          workingDirectory: '$(appDir)'
      - task: CmdLine@2
        displayName: 'Upload app to DeployGate'
        inputs:
          script: |
            curl -X POST -H "Authorization: token $(deployGate_OrganizationApiKey)" "https://deploygate.com/api/users/$(deployGate_OrganizationName)/apps" -F "file=@${{environment.iOSAppPath}}" -F "distribution_name=$(branchName)" -F "message=$(Build.Reason) triggered build by $(Build.BuildNumber)"
          workingDirectory: '$(appDir)'
      - task: PublishPipelineArtifact@1
        displayName: 'Publish Artifact'
        inputs:
          targetPath: '$(appDir)/ios/build'
          artifactType: 'pipeline'
          artifactName: '${{environment.name}}.ipa'
          parallel: true
        condition: succeeded()
