trigger:
  branches:
    include:
      - 'master'
  paths:
    include:
      - '.tool-versions'
      - '.azure-pipelines/**'
      - 'example-app/SantokuApp'
    exclude:
      - 'example-app/SantokuApp/README.md'

pr: none

name: $(date:yyyyMMdd)$(rev:.rr)

extends:
  template: deploy.yaml
