name: Docs

on:
  pull_request:
    branches:
      - master
    paths:
      - '**.md'
      - content/**
      - images/**
      - layouts/**
      - resources/**
      - themes/**
      - .gitmodules
      - .markdownlint.js
      - .textlintrc
      - .package.json
      - .package-lint.json
      - .github/workflows/docs.yaml
    types:
      - opened
      - synchronize
      - reopened

jobs:
  lint:
    name: Run lints
    runs-on: ubuntu-20.04
    env:
      REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      # Cache '.npm' to speed up clean-install when package-lock.json is updated.
      # Loosened up the restore-keys a bit, as it doesn't have to match the contents of package-lock.json exactly.
      - name: Cache .npm
        id: cache-npm
        uses: actions/cache@v2
        with:
          path: ~/.npm
          # If cache is corrupted, increment prefixed number.
          key: 1-${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            1-${{ runner.os }}-npm-

      # If package-lock.json matches, node_modules will also match.
      # So, cache node_modules directly to skip install step.
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: SantokuApp/node_modules
          # If cache is corrupted, increment prefixed number.
          key: 1-${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm clean-install

      - name: Set up reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Lint (textlint)
        run: |
          npm run -s lint:text | ${REVIEWDOG} -tee -f eslint -name textlint -reporter github-pr-review -fail-on-error

      - name: Lint (markdownlint)
        # https://github.com/reviewdog/action-markdownlint/blob/master/entrypoint.sh
        run: |
          npm run -s lint:md | ${REVIEWDOG} -tee -efm="%f:%l:%c %m" -efm="%f:%l %m" -name markdownlint -reporter github-pr-review -fail-on-error

  build:
    name: Build documents
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.80.0'

      - name: Build
        run: hugo --minify

      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mobile-app-crib-notes
          path: ./public
          retention-days: 30
