name: Deploy

on:
  workflow_run:
    workflows:
      - GitHub Pages
    branches:
      - master
    types:
      - completed

jobs:
  deploy-pages:
    name: Deploy Pages
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mobile-app-crib-notes
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
