name: GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths:
      - docs/**
      - src/**
      - static/**
      - landing-page/**
      - .editorconfig
      - .eslintrc.js
      - .htmltest.yaml
      - .markdownlint.js
      - .prettierrc.js
      - .stylelintrc.js
      - .textlintrc.js
      - babel.config.js
      - docusaurus.config.js
      - package.json
      - package-lock.json
      - prh.yaml
      - README.md
      - tsconfig.json
      - .github/workflows/gh-pages.yaml
      - .github/workflows/gh-pages-deploy.yaml
      - .github/workflows/report.yaml
    types:
      - opened
      - synchronize
      - reopened

jobs:
  lint:
    name: Lints
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      # Cache '.npm' to speed up clean-install when package-lock.json is updated.
      # Loosened up the restore-keys a bit, as it doesn't have to match the contents of package-lock.json exactly.
      - name: Cache .npm
        id: cache-npm
        uses: actions/cache@v2
        with:
          path: ~/.npm
          # If cache is corrupted, increment prefixed number.
          key: 1-${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            1-${{ runner.os }}-npm-

      # If package-lock.json matches, node_modules will also match.
      # So, cache node_modules directly to skip install step.
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          # If cache is corrupted, increment prefixed number.
          key: 1-${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm clean-install

      - name: Lint (textlint)
        if: always()
        run: |
          npm run -s lint:text -- -f checkstyle -o textlint-results

      - name: Lint (markdownlint)
        if: always()
        run: |
          npm run -s lint:md 2>&1 | sed -e 's/^/e:/' > markdownlint-results

      - name: Lint (ESLint)
        if: always()
        run: |
          npm run -s lint:es -- -f eslint-formatter-rdjson  -o eslint-results

      - name: Lint (TypeScript)
        if: always()
        run: |
          npm run -s lint:tsc > tsc-results.txt

      - name: Lint (stylelint)
        if: always()
        run: |
          npm run -s lint:css -- -f json -o stylelint-results

      - name: Archive workflow results
        uses: actions/upload-artifact@v2
        with:
          name: workflow-results
          path: |
            jest-junit
            *-results

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      # Cache '.npm' to speed up clean-install when package-lock.json is updated.
      # Loosened up the restore-keys a bit, as it doesn't have to match the contents of package-lock.json exactly.
      - name: Cache .npm
        id: cache-npm
        uses: actions/cache@v2
        with:
          path: ~/.npm
          # If cache is corrupted, increment prefixed number.
          key: 1-${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            1-${{ runner.os }}-npm-

      # If package-lock.json matches, node_modules will also match.
      # So, cache node_modules directly to skip install step.
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          # If cache is corrupted, increment prefixed number.
          key: 1-${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm clean-install

      - name: Build documents
        run: npm run build

#      - name: Run htmltest
#        uses: docker://wjdp/htmltest:v0.14.0
#        with:
#          args: --conf .htmltest.yaml

      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mobile-app-crib-notes
          path: ./build
          retention-days: 30
