name: Report

on:
  workflow_run:
    workflows:
      - App
    types:
      - completed

jobs:
  report:
    name: Report
    runs-on: ubuntu-latest
    steps:
      - name: Jest results
        uses: dorny/test-reporter@v1
        if: ${{ always() && steps.artifact.outputs.jest-junit }}
        with:
          name: Jest results
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact: workflow-results
          path: jest-junit
          reporter: jest-junit
