name: Report

on:
  workflow_run:
    workflows:
      - App
      - GitHub Pages
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    env:
      REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    if: >
      ${{ github.event.workflow_run.event == 'pull_request'}}
    steps:
      - name: Set up reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Extract workflow result
        id: artifact
        uses: marocchino/on_artifact@v1
        with:
          name: workflow-results

      - name: textlint results
        if: ${{ steps.artifact.outputs..textlint-results.txt }}
        run: |
          reviewdog -tee -reporter=github-pr-review -f=checkstyle -name=textlint < .textlint-results.txt

      - name: markdownlint results
        if: ${{ steps.artifact.outputs..markdownlint-results.txt }}
        run: |
          reviewdog -tee -reporter=github-pr-review -efm="%t:%f:%l:%c %m" -name=markdownlint < .markdownlint-results.txt

      - name: ESLint results
        if: ${{ steps.artifact.outputs..eslint-results.json }}
        run: |
          reviewdog -tee -reporter=github-pr-review -f=rdjson -name=ESLint < .eslint-results.json

      - name: TypeScript results
        if: ${{ steps.artifact.outputs..tsc-results.txt }}
        run: |
          reviewdog -tee -reporter=github-pr-review -f=tsc -name=TypeScript < .tsc-results.txt

      - name: stylelint results
        if: ${{ steps.artifact.outputs..stylelint-results.json }}
        run: |
          jq -r '.[] | {source: .source, warnings:.warnings[]} | "\(.source):\(.warnings.line):\(.warnings.column):\(.warnings.severity): \(.warnings.text) [\(.warnings.rule)](https://stylelint.io/user-guide/rules/\(.warnings.rule))"' \
             < .stylelint-results.json | reviewdog -tee -reporter=github-pr-review -efm="%f:%l:%c:%t%*[^:]: %m" -name=stylelint

      - name: Jest results
        uses: dorny/test-reporter@v1
        if: ${{ steps.artifact.outputs.jest-junit.xml }}
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          artifact: workflow-results
          name: Jest results
          path: 'jest-junit.xml'
          reporter: jest-junit
